import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import {Toaster} from "react-hot-toast";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const quickSande = Quicksand({subsets: ['latin']});

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quickSande.className}>
        <ReactQueryProvider>
         <GoogleOAuthProvider clientId="709883582241-iacq0m63kn2nq76c86or2ouha6f0mmrh.apps.googleusercontent.com">
           <Toaster />
           {/* <ReactQueryDevtools /> */}
           {children}
          </GoogleOAuthProvider>
         </ReactQueryProvider>
      </body>
    </html>
  );
}
